### ISSUE TITLE
Azulejo broken on Ubuntu

### ISSUE THREAD

**Issue by linqcan** [plainas/azulejo#1]
Just recently did a system update of my Ubuntu 12.10 system and since then Azulejo can not bind my shortcuts any more.

<pre>
Xlib.protocol.request.QueryExtension
Xlib.protocol.request.QueryExtension

** (run.py:3181): WARNING **: Binding '<Super>y' failed!
</pre>

Please let me know how I can supply more information to help you!

**Comment by plainas** [comment]
Unfortunately, the whole gnome2 EOL fiasco created huge fragmentation and caused a large wave of wheel-reinventing that is still in progress on various desktops environments. This project was one more casuality among many.

I would like to port this project to GTK3, but to be honest I find the documentation and the community in general quite lacking. I use the cinnamon desktop, documentation about its window manager is nowhere to be found.

Right now, diving into [nemo](https://github.com/linuxmint/nemo)'s source code to figure out how its api works would be too time consuming. Heck, I don't even have a clue on how to set up a development environment for GTK3 projects.

If you know anybody that is willing to help, feel free to point them out this project as I myself still miss such functionality on my desktop everyday.

**Comment by linqcan** [comment]
Thank you for your answer, however, I misguided you. I'm sorry for my totally crappy issue report, I will try again:

I am running Xubuntu 12.10 and azulejo has been running fine until this Tuesday (June 11th) when, after I updated some packages, it stopped working (error message above).

**Comment by plainas** [comment]
No, I understood the issue correctly.

Azulejo relies on old stuff that is pretty much abandoned/discontinued.
You were lucky that it has been working for you, I haven't been able to use on ubuntu(unity) nor linuxmint(cinamon) for a while.
Distributions have moved on, and as they remove/change legacy stuff, applications that depend on it become unusable.

From that error message, it looks like the latest updates broke [python-keybinder](https://github.com/engla/keybinder/tree/master/python-keybinder) which azulejo uses.

At the moment, the only reasonable way forward for this project is to be ported to GTK3.

**Comment by linqcan** [comment]
Aha, I see...
That's a shame, Azulejo was saving my day (every day). Really appreciated it!

Let's hope somebody with GTK3 knowledge, and time, sees this and can help out!

**Comment by linqcan** [comment]
Out of the blue, azulejo started to work again on Ubuntu 12.10!
